<?php

namespace PhoNetworksAutogenerated;

use Pho\Framework;
use Pho\Kernel\Kernel;
use Pho\Kernel\Traits;
use Pho\Kernel\Foundation;
use Webmozart\Assert\Assert;




/*****************************************************
 * This file was auto-generated by pho-compiler
 * For more information, visit http://phonetworks.org
 ******************************************************/

class Status extends Foundation\AbstractObject {

    const T_EDITABLE = false;
    const T_PERSISTENT = true;
    const T_EXPIRATION =  0;
    const T_VERSIONABLE = false;
    
    const DEFAULT_MOD = 0x0e444;
    const DEFAULT_MASK = 0xeeeee;

    public function __construct(\Pho\Kernel\Kernel $kernel, \Pho\Kernel\Foundation\AbstractActor $actor, \Pho\Lib\Graph\GraphInterface $graph , string $status)
    {
        parent::__construct($kernel, $actor, $graph);
        Assert::maxLength($status, 140);
$this->attributes()->status = $status;
$this->attributes()->create_time = time();

    }

    protected function onIncomingEdgeRegistration(): void
    {
        $this->registerIncomingEdges(UserOut\Post::class);
        $this->registerIncomingEdges(UserOut\Like::class);
    }

}

/*****************************************************
 * Timestamp: 1499811736
 * Size (in bytes): 1392
 * Compilation Time: 3840
 * 86399bc4d75a6ce0d18c900e1654dce3
 ******************************************************/