<?php
require "vendor/autoload.php";
use Pho\Kernel\Kernel as Kernel;
$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();
$configs = array(
  "services"=>array(
    "database" => getenv('DATABASE_URI'),
    "storage" => getenv("STORAGE_URI"),
    "default_objects" => [
            "graph" => \PhoNetworksAutogenerated\Graph::class,
            "founder" => \PhoNetworksAutogenerated\User::class,
    ]
  )
);
$kernel = new \Pho\Kernel\Kernel($configs);
$kernel->boot();
$founder = $kernel->founder();
$graph = $kernel->graph();
