<?php

namespace PhoNetworksAutogenerated\UserOut;

use Pho\Kernel\Traits\HydratingEdgeTrait;
use Pho\Lib\Graph\NodeInterface;
use Pho\Lib\Graph\PredicateInterface;
use Pho\Framework;



/*****************************************************
 * This file was auto-generated by pho-compiler
 * For more information, visit http://phonetworks.org
 ******************************************************/

class Post extends Framework\ActorOut\Write {

    
    use HydratingEdgeTrait;
    

    const HEAD_LABEL = "post";
    const HEAD_LABELS = "posts";
    const TAIL_LABEL = "author";
    const TAIL_LABELS = "authors";
    
    const SETTABLES_EXTRA = [\PhoNetworksAutogenerated\Status::class];

    public function __construct(NodeInterface $tail, NodeInterface $head, ?PredicateInterface $predicate = null) 
    {
        parent::__construct($tail, $head, $predicate);
        $this->kernel = $GLOBALS["kernel"];
        //$this->persist();
    }

}

/* Predicate to load as a partial */
class PostPredicate extends Framework\ActorOut\WritePredicate
{
    protected $binding = true;
    const T_CONSUMER = true;
    const T_PERSISTENT = true;
}
/* Notification to load if it's a subtype of write or mention. */
class PostMention extends Framework\ActorOut\WriteMention
{

}
/*****************************************************
 * Timestamp: 
 * Size (in bytes): 1484
 * Compilation Time: 46594
 * da1b8647a192fca6264dafb805bf479a
 ******************************************************/