<?php

namespace PhoNetworksAutogenerated;

use Pho\Framework;
use Pho\Kernel\Kernel;
use Pho\Kernel\Traits;
use Pho\Kernel\Foundation;




/*****************************************************
 * This file was auto-generated by pho-compiler
 * For more information, visit http://phonetworks.org
 ******************************************************/

class UserEditable extends User {

    const T_EDITABLE = true;

    

}

/*****************************************************
 * Timestamp: 1501461738
 * Size (in bytes): 2346
 * Compilation Time: 3434
 * e64cf8335098e7a03ebd665e7c424c27
 ******************************************************/