<?php

/*
 * This file is part of the Pho package.
 *
 * (c) Emre Sokullu <emre@phonetworks.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */


namespace Pho\Kernel;

class CustomFounderTestCase extends TestCase
{
    protected function getKernelConfig()
    {
        $configs = parent::getKernelConfig();
        $configs["default_objects"] = [
            "graph" => \PhoNetworksAutogenerated\Graph::class,
            "founder" => \PhoNetworksAutogenerated\User::class,
        ];
        return $configs;
    }

    protected function startKernel($founder=null): void
    {
      $this->configs = $this->getKernelConfig();
      $this->kernel = new Kernel($this->configs);
      $founder = new \PhoNetworksAutogenerated\User($this->kernel, $this->kernel->space(), "123456");
      $this->kernel->boot($founder);
      $this->graph = $this->kernel->graph();
    }
}
