<?php

/*
 * This file is part of the Pho package.
 *
 * (c) Emre Sokullu <emre@phonetworks.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Pho\Kernel;

class DefaultObjectsAreStandardTest extends TestCase
{

    public function testSimple() {
        $this->kernel->logger()->info("testSimple started");
        $this->flushDBandRestart();
        $this->kernel->logger()->info("DB flushed and restarted");
        $this->assertInstanceOf(Kernel::class, $this->kernel);   
        $this->kernel->logger()->info("instance check for kernel completed.");
        $this->assertInstanceOf(\PhoNetworksAutogenerated\User::class, $this->kernel->founder());
        $this->kernel->logger()->info("instance check for founder completed.");
        $u = new \PhoNetworksAutogenerated\User($this->kernel, $this->graph, "123456");
        $this->kernel->logger()->info("The User object is created");
        $this->created[] = $u->id();
        $this->kernel->logger()->info("About to post.");
        $post = $u->post("my first post");
        $this->kernel->logger()->info("Posted.");
        $this->assertInstanceOf(\PhoNetworksAutogenerated\Status::class, $post);
    }

    /**
     * @todo complete
     */
    public function testActorJoin() {
    }

    /**
     * @todo complete
     */
    public function testActorLeave() {

    }

}