<?php

/*
 * This file is part of the Pho package.
 *
 * (c) Emre Sokullu <emre@phonetworks.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Pho\Kernel;

class EntityDestroyTest extends DefaultObjectsAreStandardTest 
{

    public function testEdgeCounts() {
        $this->flushDBandRestart();
        $user1 = new \PhoNetworksAutogenerated\User($this->kernel, $this->graph, "123456");
        $user2 = new \PhoNetworksAutogenerated\User($this->kernel, $this->graph, "123456");
        $graph = $this->kernel->graph();
        $space = $graph->context();
        eval(\Psy\sh());
        $content = $user->post("emre sokullu");
        $this->assertCount(0, $content->getLikers());
        $this->assertCount(0, $this->kernel->founder()->getLikes());
        $this->kernel->founder()->like($content);
        $this->assertCount(1, $this->kernel->founder()->getLikes());
        $this->assertCount(1, $content->getLikers());
        $this->assertCount(0, $user->getFollows());
        $this->assertCount(0, $this->kernel->founder()->getFollowers());
        $user->follow($this->kernel->founder());
        $this->assertCount(1, $user->getFollows());
        $this->assertCount(1, $this->kernel->founder()->getFollowers());
    }  

}