<?php

/*
 * This file is part of the Pho package.
 *
 * (c) Emre Sokullu <emre@phonetworks.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */


namespace Pho\Kernel;

class GraphMemberChangePersistenceTest extends TestCase
{
    public function testParticleAdded() {
        $this->flushDBandRestart();
        $count_initial = count($this->kernel->graph()->members());
        $user = new \PhoNetworksAutogenerated\User($this->kernel, $this->graph, "123456");
        $count_final = count($this->kernel->graph()->members());
        $this->assertEquals(1, $count_final-$count_initial);
        $status = $user->post("status");
        $this->assertInstanceOf(\PhoNetworksAutogenerated\Status::class, $status);
        $count_final = count($this->kernel->graph()->members());
        $this->assertEquals(2, $count_final-$count_initial);
    }
}