<?php

/*
 * This file is part of the Pho package.
 *
 * (c) Emre Sokullu <emre@phonetworks.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Pho\Kernel;

class PlayTest extends TestCase
{
    public function testSimple() {
        $this->assertInstanceOf(Kernel::class, $this->kernel);   
        include("tests/assets/compiled/User.php");
        include("tests/assets/compiled/Status.php");
        include("tests/assets/compiled/StatusOut/Mention.php");
        include("tests/assets/compiled/UserOut/Follow.php");
        //include("tests/assets/compiled/UserOut/FollowPredicate.php");
        include("tests/assets/compiled/UserOut/Like.php");
        include("tests/assets/compiled/UserOut/Post.php");
        $u=new \PhoNetworksAutogenerated\User($this->kernel, $this->graph);
        eval(\Psy\sh());
    }

}