<?php

/*
 * This file is part of the Pho package.
 *
 * (c) Emre Sokullu <emre@phonetworks.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Pho\Kernel\Acl;

class AclTestCase extends \Pho\Kernel\CustomFounderTestCase 
{
    protected $user, $subscriber, $stranger, $anonymous;

    public function setUp() {
        parent::setUp();
        $this->user = new \PhoNetworksAutogenerated\User($this->kernel, $this->graph, "123456");
        $this->subscriber = new \PhoNetworksAutogenerated\User($this->kernel, $this->graph, "123456");
        $this->subscriber->follow($this->user);
        $this->stranger = new \PhoNetworksAutogenerated\User($this->kernel, $this->graph, "123456");
        $this->anonymous = new \PhoNetworksAutogenerated\User($this->kernel, $this->kernel->space(), "123456");
        $this->graph->acl()->chmod(0x0f755); // default value
    }
}