<?php

/*
 * This file is part of the Pho package.
 *
 * (c) Emre Sokullu <emre@phonetworks.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Pho\Kernel\Acl;

use Pho\Kernel\Foundation\Exceptions;

class DeniedPermissionAclTest extends AclTestCase 
{

    public function testExecutePermissionExceptionPositive() {
        //eval(\Psy\sh());
        $post = $this->user->post("my first post");
        //$post->acl()->chmod(0x07000); // others can't read
        //$this->expectException(Exceptions\ExecutePermissionException::class);
        $this->stranger->like($post); // subscribe
        $this->assertTrue($post->hasLiker($this->stranger->id()));
    }

    public function testExecutePermissionExceptionNegative() {
        $post = $this->user->post("my first post");
        $post->acl()->chmod(0x07000); // others can't read
        $this->expectException(Exceptions\ExecutePermissionException::class);
        $this->stranger->like($post); // subscribe
    }

    public function testWritePermissionExceptionNegative() {
        $this->graph->acl()->chmod(0x04444); // read-only
        $this->expectException(Exceptions\WritePermissionException::class);
        $post = $this->user->post("my first post");
    }

    public function testReadPermissionExceptionPositive() {
        $post = $this->user->post("my first post");
        $this->assertInstanceOf(\PhoNetworksAutogenerated\Status::class, $this->stranger->consume($post));
    }

    public function testReadPermissionExceptionNegative() {
        $post = $this->user->post("my first post");
        $post->acl()->chmod(0x04000);
        $this->assertInstanceOf(\PhoNetworksAutogenerated\Status::class, $this->user->consume($post));
        $this->expectException(Exceptions\ReadPermissionException::class);
        $this->stranger->consume($post);
    }

}