<?php

namespace PhoNetworksAutogenerated\UserOut 
{

use Pho\Kernel\Bridge\EdgeHydratorTrait;
use Pho\Lib\Graph\NodeInterface;
use Pho\Lib\Graph\PredicateInterface;
use Pho\Framework;



/*****************************************************
 * This file was auto-generated by pho-compiler
 * For more information, visit http://phonetworks.org
 ******************************************************/

class Follow extends Framework\ActorOut\Subscribe {

    
    use EdgeHydratorTrait;
    

    const HEAD_LABEL = "follow";
    const HEAD_LABELS = "follows";
    const TAIL_LABEL = "follower";
    const TAIL_LABELS = "followers";
    

    const FORMABLES = [\PhoNetworksAutogenerated\User::class];
    

    public function __construct(NodeInterface $tail, NodeInterface $head, ?PredicateInterface $predicate = null) 
    {
        parent::__construct($tail, $head, $predicate);
        $this->kernel = $GLOBALS["kernel"];
        //$this->persist();
    }

}

/* Predicate to load as a partial */
class FollowPredicate extends Framework\ActorOut\SubscribePredicate
{
    protected $binding = false;
    const T_CONSUMER = true;
    const T_FORMATIVE = true;
    const T_PERSISTENT = true;
}
/* Notification to load if it's a subtype of write or mention. */

}

/*****************************************************
 * Timestamp: 
 * Size (in bytes): 1475
 * Compilation Time: 285649
 * e4fc1d81fa1b98a8553c521f3dacee52
 ******************************************************/