<?php

namespace PhoNetworksAutogenerated;

use Pho\Framework;
use Pho\Kernel\Kernel;
use Pho\Kernel\Traits;
use Pho\Kernel\Foundation;




/*****************************************************
 * This file was auto-generated by pho-compiler
 * For more information, visit http://phonetworks.org
 ******************************************************/

class Status extends Foundation\AbstractObject {

    const T_EDITABLE = false;
    const T_PERSISTENT = true;
    const T_EXPIRATION =  0;
    const T_VERSIONABLE = false;
    
    const DEFAULT_MOD = 0x0e444;
    const DEFAULT_MASK = 0xeeeee;

    private $txt;

    public function __construct(\Pho\Kernel\Kernel $kernel, \Pho\Kernel\Foundation\AbstractActor $actor, \Pho\Lib\Graph\GraphInterface $graph, string $txt)
    {
        parent::__construct($kernel, $actor, $graph);
        $this->txt = $txt;
    }

    public function sayWhat() {
        echo $this->txt;
    }

    protected function onIncomingEdgeRegistration(): void
    {
        $this->registerIncomingEdges(UserOut\Post::class);
        $this->registerIncomingEdges(UserOut\Like::class);
    }

}

/*****************************************************
 * Timestamp: 1499688374
 * Size (in bytes): 1011
 * Compilation Time: 285652
 * abb20db53ea7158592fab5fdf9191610
 ******************************************************/